dist: xenial

language: python

addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO_ENV="django>=2.2,<3.0"
  - DJANGO_ENV="django>=3.0<3.1"

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO_ENV="django>=3.0<3.1"

install:
  - pip install pip poetry -U
  - poetry install --extras "$DJANGO_ENV"
  - npm install --dev
script:
  - make qa
  - make coverage
after_success:
  - codecov
branches:
  only:
    - master
